import { reactive } from "vue";

export const store = reactive({
    api_key: "bfa02625404f494fc92249458d5ba46f",
    apiUrlMovies: "https://api.themoviedb.org/3/search/movie",
    apiUrlSeries: "https://api.themoviedb.org/3/search/tv",
    apiUrlImg: "https://image.tmdb.org/t/p/w342",
    arrayMovies: [],
    arraySeries: [],
    searchInput: "",

    languageToCountry: {
        af: 'za',
        ar: 'sa',
        bg: 'bg',
        bn: 'bd',
        ca: 'es',
        cs: 'cz',
        cy: 'gb',
        da: 'dk',
        de: 'de',
        el: 'gr',
        en: 'gb',
        es: 'es',
        et: 'ee',
        fa: 'ir',
        fi: 'fi',
        fr: 'fr',
        gu: 'in',
        he: 'il',
        hi: 'in',
        hr: 'hr',
        hu: 'hu',
        id: 'id',
        it: 'it',
        ja: 'jp',
        kn: 'in',
        ko: 'kr',
        lt: 'lt',
        lv: 'lv',
        ml: 'in',
        mr: 'in',
        ms: 'my',
        nl: 'nl',
        no: 'no',
        pa: 'in',
        pl: 'pl',
        pt: 'pt',
        ro: 'ro',
        ru: 'ru',
        sk: 'sk',
        sl: 'si',
        sq: 'al',
        sr: 'rs',
        sv: 'se',
        ta: 'in',
        te: 'in',
        th: 'th',
        tr: 'tr',
        uk: 'ua',
        ur: 'pk',
        vi: 'vn',
        zh: 'cn',
        zu: 'za',
    }
});